# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  packages: true

script:
  - Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'
  
deploy:
  provider: pages
  local_dir: _book
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
