# (PART) Conclusion {- #part-conclusion} 

# Summary and general discussion

Attention is the solution to our limited capacity to process all the information that is available to us. Without attention, we would inevitably lose ourselves in the infinitude of present moment sensory input, past memories, and future plans. As such, attention is by definition a limited capacity process---otherwise it would fall prey to the very problem it was meant to solve. But what if there was a way to enhance attention beyond its limited capacity? To be a little bit faster to find what we are looking for, a little more resistant to distraction, a little more vigilant? 

In this thesis, I studied whether attention can be enhanced through non-invasive brain stimulation, using transcranial Direct Current Stimulation (tDCS) in particular. Because attention is a multi-faceted process involving distributed neural networks, I studied both its spatial and its temporal form, and targeted different brain regions.

In Chapter \@ref(sacc-tDCS), I examined whether tDCS over the frontal eye fields can improve spatial attention. Because the frontal eye fields are primarily involved in eye movements, I used eye tracking to measure the effect of tDCS, while participants made eye movements to sudden onset targets as fast as possible. We predicted that anodal tDCS would increase baseline activity in the frontal eye fields, and would thereby decrease the latency of eye movements. However, eye movement latency during anodal tDCS did not differ from baseline, or from cathodal tDCS, even though a previous study had reported exactly that [@Kanai2012]. tDCS also did not affect the accuracy of eye movements.

In Chapter \@ref(AB-tDCS-EEG) and Chapter \@ref(AB-tDCS-sEBR), I investigated the effects of tDCS on temporal attention, using the attentional blink task. This study built upon earlier work from our group [@London2015], which showed that the effects of tDCS on the attentional blink differ systematically across individuals. Specifically, the effects of anodal and cathodal tDCS were negatively correlated: individuals that benefited from anodal tDCS tended to worsen during cathodal tDCS (or vice versa). In Chapter \@ref(AB-tDCS-EEG), we first attempted to replicate this result, using a number of different analyses to quantify replication success. All of these suggested our study was not a successful replication of @London2015. In Chapter \@ref(AB-tDCS-sEBR), we examined whether baseline dopamine levels could predict the effects of tDCS on the attentional blink. We measured spontaneous eye blink rate (sEBR) as an index of dopamine, but sEBR was not associated to changes in attentional blink size following tDCS. Attentional blink size and sEBR were also uncorrelated before tDCS onset (in contrast to an earlier study by @Colzato2008), which probably partly explains the null result.

All the studies on tDCS and attention in this thesis have thus resulted in null findings. In fact, every study from our group that tried to affect attention with transcranial electrical stimulation (tES; including both tDCS and tACS) has produced null results [@VanSchouwenburg2019; @VanSchouwenburg2018]. The rest of this chapter is focused on discussing these discouraging results. In the next sections, I offer three overlapping categories of explanations: concerning tES and attention specifically, tES studies more generally, and psychological science as a whole. I end with some directions for future research on tES and attention, as well as some general conclusions we can draw from this thesis and the current state of the field.

## tES and attention

Perhaps the literature review I presented in Chapter \@ref(tDCS-att-review) already hinted at this outcome. There, we reviewed all published studies (until mid-2016) that used tES to study attention, primarily selective (visual search, spatial attention) and sustained attention. In each of these domains, we found a few studies with promising outcomes, where tES produced a sizable enhancement of attention. But these were always accompanied by other studies where tES actually worsened task performance, only worked under certain conditions, or had no clear effects at all. We found it difficult to get at the source of these differences in outcome, as the studies also varied greatly in their experimental design and choice of stimulation parameters. But in general, we can conclude that enhancements in attention are not easily obtained with tES.

One potential explanation is that the behavioral effects of attention itself are already rather subtle, at least as they are typically measured in the lab. For example, in the Posner task---one of the most widely used paradigms to study attention---participants are cued where a target will later appear, allowing them to shift their attention to this location. The maximal benefit that this cue provides (depending on its predictiveness, location, and other parameters) appears to be a decrease in response times to the target of ca. 50 ms [@Chica2014]. Likewise, attention may also enhance our sensitivity to visual stimuli at a certain location, which according to one study manifests as a 2--8 percentage point increase in contrast [@Carrasco2004]. It seems unlikely that tES would be able to further enhance these effects by a large margin---rather by a small fraction.

There is a different but related underlying argument here: that the attentional system is functioning close to optimally in healthy individuals. There might simply not be very much room for improvements that tES could bring. In Chapter \@ref(sacc-tDCS), we suggested this as a possible explanation for our null findings, as baseline eye movement latency in our participants was already very fast. One could argue that if task performance is already at ceiling, then cathodal tDCS should still lead to impairments. However, considering that multiple attention-related brain areas will be active at any given moment, stimulation-induced changes in one area could be compensated for by the rest of the network. For instance, spatial attention seems to be governed by a balance in activity between the two hemispheres [@Kinsbourne1970]. Attempts to disrupt this balance by increasing (decreasing) activity in one hemisphere with anodal (cathodal) tDCS could prompt a compensatory response in the other hemisphere. 

This inter-hemispheric balance is already disrupted in hemispatial neglect patients, who typically have a lesion in the right hemisphere [@Vallar1986]. A number of studies have attempted to use tDCS to restore this balance, by applying anodal tDCS to the lesioned hemisphere and/or cathodal tDCS to the unlesioned hemisphere (see Chapter \@ref(tDCS-att-review). All but one of these reported improvements following tDCS. tES might thus be more effective in clinical samples, where the margins for improvement are larger. Alternatively, tES could also be more effective with repeated applications in multiple sessions (which is typical in clinical studies, to evoke more long-term changes).

### tES to enhance sustained attention?

Under some circumstances, the limits of the attentional system become readily apparent, even in otherwise healthy individuals. This was one of the reasons we decided to test whether tDCS can be used to attenuate the attentional blink (Chapters \@ref(AB-tDCS-EEG) and  \@ref(AB-tDCS-sEBR)). However, perhaps the limits to attention come most clearly into view when it has to be sustained for a prolonged period of time.

In Chapter \@ref(MFBrain), we examined changes in sustained attention by having participants perform a vigilance task for 80 consecutive minutes, while we recorded their EEG. We observed the classical vigilance decrement: task performance dropped steadily and reached a low-point after just 20--30 minutes. After 60 minutes, an unexpected motivation boost partially restored task performance, but participants were not able to maintain this level until the end of the experiment. In the EEG, we found that phase clustering of theta-band oscillations was closely associated with these behavioral changes, suggesting that the timing of the neural response to the stimulus became more variable as performance decreased.

Our literature review (Chapter \@ref(tDCS-att-review)) also included studies that paired tES with sustained attention tasks. Two studies indeed reported that tDCS prevented performance declines related to time-on-task [@Nelson2014] or sleep deprivation [@McIntire2014]. However, two recent experiments from our group [@VanSchouwenburg2019] using the same task as in Chapter \@ref(MFBrain) were not as successful. First, anodal or cathodal tDCS over the medial frontal cortex delivered after 20 minutes of task performance did not affect the vigilance decrement. Second, partly inspired by the changes in theta-band oscillations we identified in Chapter \@ref(MFBrain), @VanSchouwenburg2019 attempted to stimulate the medial frontal cortex with tACS instead. But this approach also did not seem fruitful. If anything, theta tACS appeared to accelerate the vigilance decrement, relative to a control condition with alpha-band stimulation. 

All in all, while enhancement of sustained attention could be a promising application of tES, many more studies will be need to determine whether and how this can be done. One complicating factor is that the vigilance decrement itself remains to be fully understood. As we also showed in Chapter \@ref(MFBrain), both motivation and depletion of resources could play a role, as well as other relevant factors we did not investigate, such as mind wandering or subjective feelings of fatigue. It is not clear which of these processes were affected by tES in the studies that proved successful, nor which of these would be an optimal target for future studies.

## tES challenges

The mixed results we and others obtained probably also stem from fundamental uncertainties about the tES technique. These hold regardless of whether tES is applied in attention research, or in other domains. M Many of these have long been known [@Reato2019; @Bikson2019] and must live in the back of the mind of most scientists that use tES. But it may be that---ever since the pioneering studies that successfully applied tDCS to the human motor cortex [@Nitsche2000; @Nitsche2001]---we have become so inspired that we have taken too great a liberty with the technique, and have not given enough thought to its limitations. I will therefore reiterate some of the most pertinent factors that determine the outcome of tES below[^tES-factors].

__The cellular effects of tES are subtle and complex__. The physiological effects of tES are usually summarized following the "anodal-excitation / cathodal-inhibition" dichotomy [@Jacobson2012]. That is, the effects of tDCS are ascribed to changes in the neural membrane potential, where anodal tDCS depolarizes neurons and thus has an excitatory effect, while cathodal tDCS hyperpolarizes neurons and thus has an inhibitory effect. This simple heuristic is much more complicated in reality, which makes it difficult to predict the overall outcome of tDCS.

First, the effects are highly dependent on the orientation of the electric field. Anodal (cathodal) tDCS is only excitatory (inhibitory) when the polarization is applied at the cortical surface, and the neurons are exactly parallel to the electric field, with the dendrites closest to the electrode. For inversely oriented neurons, the polarization will also be inverted; for tangentially oriented neurons, there will be almost no polarization at all. Because the cortex is highly folded, the orientation of neurons with respect to the scalp surface varies greatly, so applying tDCS at the scalp should always lead to a mix of these three extremes (and all possibilities in between). [@Reato2019]

Second, all of this concerns only the effects of at the soma, but the net effect of tES is based on the membrane potential in all parts of the neuron [@Jackson2016]. Even for a neuron that is perfectly parallel to the electric field, the apical dendrites will be polarized in the opposite direction as the soma [@Bikson2019]. This is particularly important for the effects of tES on synaptic plasticity, which could even go in the opposite direction to the online effects [@Kronberg2017].

Third, the direct effects of the electric field on membrane polarization are very subtle, so it is unlikely that these are the whole story. Recent studies have measured the electric field that tDCS at 2 mA generates in the human brain, which peaked at .5 [@Opitz2016] -- 0.8 [@Huang2017] V/m (though note that a lot studies stimulate at 1 mA instead). Earlier studies estimated the maximum change in the membrane potential to be .1 [@Bikson2004] -- .3 mV per V/m [@Radman2009]. So in the best case scenario, tDCS can result in a polarization of .05 -- .25 mV [@Bikson2019]. Although tDCS was never presumed to directly elicit action potentials, it is still prudent to realize this effect amounts to only about 1% of the change necessary to do so (as a depolarization of at least 15 mV would be needed to go from the resting threshold at -70 mV to the firing threshold at -50 -- -55 mV). @Voroslakos2018 argue that this is simply too weak to elicit reliable effects. They showed that in the living rat brain, stimulation only affected neuronal spiking and membrane potentials at field strengths exceeding 1 V/m. They then measured the electric fields in human cadavers at different intensities of tDCS, and concluded that achieving a field strength of 1 V/m would require as much as 4--6 mA tDCS. Others have concluded that the changes in the electric field produced by conventional tDCS still fall within the lower bound of effectiveness [@Huang2017].

__The current flow induced by tES is not spatially specific__. Typically, tES studies are focused on one particular brain area, based on some evidence of its involvement in the cognitive process that the researcher aims to affect. One of the electrodes (in tDCS, usually the anode) is then placed over this area, typically based on a scalp position in the 10-20 system, or with MRI-based neuronavigation. However, this does not guarantee that a sufficiently strong electric field is induced in this brain area, nor that this will happen _only_ in this brain area. 

For one, a tES montage always consists of two electrodes, so the "reference" electrode also has to be placed somewhere on the body. In the studies in this thesis, we placed it on the forehead, as this is simply what many studies before us did. However, this will lead to opposite polarity stimulation of the brain tissue underneath this electrode. Some opt to circumvent this issue by placing the electrode elsewhere on the body, such as the shoulder. But this increases the inter-electrode distance, which can decrease the size of the effect [@Moliadze2010; @Opitz2015]. 

Second, the current flow is not restricted to the area under the electrodes, as the simulation in Figure \@ref(fig:figure-1-tDCS)D also shows. The induced electric field is always more diffuse [@Opitz2015], and may even peak at other locations, such as in between the electrodes [@Saturnino2017]. For some montages, the actual pattern of current flow can differ vastly from the intended one [@Karabanov2019]. This is especially true if there is an opportunity for the current to shunt through the skin---which may attenuate the current by 60% or more [@Voroslakos2018]---or other highly conductive tissues, such as cerebrospinal fluid. 

Finally, even if a perfectly focal current distribution were achievable, tES can still have more distal effects, as the activity it induces in the target brain area may spread through the network of other areas it is connected with [@Knotkova2019; @Wokke2015].

All of this makes it very difficult to use tES as a tool to localize functions in the brain, or to predict the outcomes of tES according to which brain areas it affects [@Karabanov2019]. Researchers should therefore generally try to model the current flow, especially for novel montages, at least to be aware that spatially specific conclusions might be difficult to draw. In addition, tES can be combined with neuroimaging techniques to provide more clues as to which brain areas and/or processes were affected (also see the [Future directions](#discussion-future) section for these and other recommendations). 

__The parameter space for tES is vast and largely unexplored__. When designing a tES study, one needs to decide on a large number of parameters, which together determine the actual dose that is delivered [@Peterchev2012]. These include the stimulation duration (e.g., 10 min, or 30 min), current intensity (e.g., 1 mA, 2 mA, or higher), stimulation waveform (tDCS, tACS, or tRNS), as well as the electrode size and shape [@Saturnino2015], electrode montage, and many more parameters. There are so many parameters and so many plausible values to set them to, that researchers are faced with a true combinatorial explosion of possibilities. 

For the intensity and duration, 1 mA for 20 minutes was the standard for a long time, based on the pioneering motor cortex-tDCS studies [@Nitsche2000; @Nitsche2001]. The problem is that there is no clear reason why these parameters should generalize to other brain areas, given that they have a different neuroanatomical structure, connectivity, and state dynamics [@Bestmann2017]. Now, longer and more intense stimulation is becoming more common (e.g. tDCS at 2 mA, or for 30 min) [@Bikson2016; @Grossman2018]. However, even in the motor cortex the canonical effects may not be elicited with these parameters. For example, while 20 minutes of 1 mA anodal tDCS typically increases motor-evoked potentials, increasing the duration to 26 minutes leads to a decrease instead [@Monte-Silva2013]. Likewise, while 10 or 20 minutes of 1 mA cathodal tDCS has an inhibitory effect on the motor cortex, increasing the current intensity to 2 mA flips the effect to excitation [@Batsikadze2013; @Parkin2018; @Samani2019].

The large variability in parameters across studies (as shown in Chapter \@ref(tDCS-att-review))---and the differences in outcome that they produce---hamper our ability to integrate across findings. Large-scale studies are necessary that systematically manipulate parameters [e.g.  @Samani2019], complemented by efficient ways to optimize them [e.g. @Violante2019].

__The effects of tES are not consistent across individuals__.  In Chapters \@ref(AB-tDCS-EEG) and \@ref(AB-tDCS-sEBR), we examined individual differences in tDCS effects on the attentional blink, and tried to account for these in terms of baseline cortical excitability and dopamine levels. However, we were not successful on either front. The change in attentional blink size in the anodal tDCS session was not related to the cathodal session, or to baseline spontaneous eye blink rates (a putative measure of dopamine). This is not to say that these factors are not important; we know that baseline brain state can fundamentally change effects of tES. For example, when the motor cortex is not stimulated at rest, but during a cognitive task or motor exercise, the canonical changes in motor-evoked potentials are no longer obtained [@Antal2007]. 

The problem is rather that there are many more factors shaping individual differences in responses to tES, of which baseline cortical excitability or neuromodulator levels may be only a small proportion. Even in motor-cortex tDCS, there is considerable variability in the response---anodal tDCS is not excitatory for everyone, nor is cathodal tDCS inhibitory for everyone [@Chew2015; @Jamil2017; @Lopez-Alonso2014; @Strube2016; @Wiethoff2014]. This may be caused by a diverse array of factors, including gender, age, baseline level of task performance, genetics, hormone levels, smoking behavior, and more [@Krause2014; @Li2015b; @Polania2018]. Even differences in head or neural anatomy may determine tES outcome, by causing differences in the pattern of current flow in the brain [@Kim2014; @Laakso2018]. This concern could be alleviated by constructing current flow models for individual participants before the experiment, and adapting the dosage or montage accordingly. Similarly, the influence of baseline cortical excitability can be revealed with neuroimaging, for example through magnetic resonance spectroscopy of GABA and glutamate levels [@Filmer2019; @Talsma2018].

[^tES-factors]: Note that this list is by no means exhaustive, partly because there are many more "known unknowns" that fall outside of the scope of the present discussion, but also because the exact mechanisms of tES are still an area of active research (for recent reviews, see e.g. @Fertonani2017, @Bestmann2014, and @Jackson2016).

## A "crisis of confidence"

Given these substantial challenges involved in tES research, the breadth of tES studies that report enhancement effects is remarkable. These cover all expanses of human cognition, such as attention, memory, perception, cognitive control, creativity, arithmetical reasoning, motor learning, and language acquisition [@Coffman2014; @Santarnecchi2015; @Dedoncker2016a]. The list of successful clinical applications of tES is perhaps even more impressive, including a diverse array of conditions such as chronic pain, aphasia, depression, schizophrenia, epilepsy, dementia, and addiction [@Lefaucheur2016a].

While this string of successes is surely exciting, some have expressed concerns that they simply cannot all be true [@Bestmann2017; @Parkin2015]. There is a lingering suspicion in the field that some of these effects must be overstated, or would fail to replicate [@Heroux2017]. @Medina2017 provide some of the most convincing evidence confirming these reservations. They subjected a random sample of tDCS studies and a collection of tDCS studies on working memory [from a meta-analysis by @Mancuso2016] to a p-curve analysis [@Simonsohn2014]. For any set of studies investigating true effects, the distribution of reported p-values should be significantly right-skewed, i.e., should contain more low p-values (e.g., .01) than higher p-values (e.g. around .05). If the shape of this distribution is different, there is reason to believe the set of studies do not have evidential value. Both of the samples examined by @Medina2017 lacked evidential value, suggesting that tDCS had no meaningful effect.

These problems are not specific to tES research, as many fields of (social scientific) research have grappled with a lack of evidential value [@Brodeur2016; @Simmons2017] and low rates of replication [@OSC2015; @Camerer2018; @Klein2018]. Particularly in the field of psychology, this realization has a sparked a crisis of confidence (also referred to as the "replication crisis") in many influential findings [@Baker2015; @Pashler2012]. The origin of the crisis can likely be traced back to the use of questionable research practices [@John2012], particularly publication bias,  hypothesizing after the results are known (HARKing), p-hacking, and low statistical power [@Munafo2017; @Bishop2019].

__Publication bias__ [@Rosenthal1979] refers to a preference for positive over negative findings, such that studies with null results remain unpublished ("in the file drawer"). Because positive results would then be over-represented in the literature [@Fanelli2012; @Franco2014], it does not accurately reflect the amount of evidence for a particular hypothesis or theory [@Ferguson2012]. Some meta-analyses of tES studies have indeed uncovered evidence for publication bias [@Mancuso2016]. In addition, a recent special issue collected over sixty null results in non-invasive brain stimulation[^frontiers]. This includes the study we report in Chapter \@ref(sacc-tDCS) [@Reteig2018b], and many other tES studies on attention [@Jacoby2018; @Learmonth2017; @Lanina2018; @VanSchouwenburg2018; @Sheldon2018; @Tseng2018; @Veniero2017].

__HARKing__ [@Kerr1998] and __p-hacking__ [@Simmons2011; @Simonsohn2014] can turn true negatives into false positives. A researcher engages in HARKing (Hypothesizing After the Results are Known) when they adapt their hypothesis to fit the observed results, if they do not fit their actual hypothesis. When p-hacking, many analyses are performed (implicitly or explicitly), but only the ones that result in a significant p-value are reported. Both p-hacking and HARKing are deceptively easy to commit, and often happen unintentionally. For example, @Medina2017 may have revealed some indications for p-hacking and/or HARKing in the sample of tDCS studies on working memory [@Mancuso2016]. They note that only 5 out of 23 studies reported a significant difference between anodal and sham tDCS, but 20 out of 23 studies reported _some_ significant result, e.g., when adding a covariate, or splitting the sample into sub-types. Both p-hacking and HARKing can be combated by preregistration [@Nosek2018] of hypotheses and analysis plans, particularly when formalized as a registered report [@Chambers2014]. Recently, the first registered report in the tES field was published [@Boayue2019], reporting a failure to replicate a study that showed tDCS can increase mind wandering [@Axelrod2015], which we had included in our review on tES and attention (Chapter \@ref(tDCS-att-review)).

A study is said to have __low statistical power__ when it has a low probability to detect an effect of a specific size. Many tES studies might chase relatively small effects that would require larger sample sizes to reliably detect [@Minarik2016]. Results from the analysis by @Medina2017 suggest that average power might currently be as low as 5--20%. This could not only lead to a lot of false negative findings, but would also inflate effect sizes for true positive findings [@Button2013].

The combined effects of these four (and other) factors can take extreme forms. For example, there are more than 600 published studies on ego depletion: the idea that self-control or willpower is weakened when the pool of limited resources that it draws on is depleted [@Inzlicht2012]. However, a recent meta analysis of these studies [@Carter2015] and a new multi-lab replication study [@Hagger2016] suggest the effect might not exist.

At this point, we cannot escape asking the following question: _Could it be that the field of tES got it this wrong_? The results presented in this thesis are not very encouraging, but given its limited scope, I cannot really speak to this question. That said, I think there is still enough reason to be optimistic. When looking at the history of TMS, the field went through similar troubles, but today has matured considerably [@Parkin2015]. Also, some tES findings appear to already be beyond doubt, such as the canonical effects on neurophysiology in animal studies, and motor-evoked potentials in humans.

Nonetheless, it is rather humbling that after almost 5000 published studies on tDCS alone[^num-tDCS], we still feel compelled to ask this question. But it is important to keep asking ourselves this question, as hubris will slow down progress even further. This is clearly demonstrated by the field of candidate gene studies: the endeavor to link genetic polymorphisms (such as the 5-HTTLPR polymorphism for the serotonin transporter gene) to psychological phenotypes (such as depression). Since the first study was published in 2003 [@Caspi2003], around 450 studies on just this one association followed [@Border2019]. However, a recent publication found no evidence for this association in samples of 62,000 and upwards, and also showed that all previous studies used sample sizes that were orders of magnitude too low to detect plausible effect sizes [@Border2019]. In other words, 16 years worth of research appears to be based on statistical noise---despite the fact that it took only two years for the first non-replication study [@Gillespie2005] to appear [@Rieckmann2009]. This story unequivocally shows that while science may be self-correcting, this process can be unacceptably slow if we do not pay heed to legitimate concerns that emerge.

[^num-tDCS]: As recorded in the "transcranial Direct Current Stimulation Studies Open Database" [<http://tdcsdatabase.com>; @Grossman2018], in May 2019.

## Future directions {#discussion-future}

Based on the studies in this thesis and the issues raised earlier in this discussion section, below I offer a few recommendations that may hopefully increase confidence in the field.

__Replicate key findings__. I have not come across many direct replications of tES studies; for example, none of the 52 studies we included in the literature review in Chapter \@ref(tDCS-att-review) were replication studies. It is probable that many studies have figured out a robust stimulation protocol that is replicable. But it also appears likely that many published studies have overestimated effects. Without replication studies, we're not able to weed out the noise from the signal. In Chapters \@ref(sacc-tDCS), \@ref(AB-tDCS-EEG), and \@ref(AB-tDCS-sEBR) of this thesis, I have tried and failed to replicate earlier findings. But none of these were sufficiently high-powered and sufficiently direct replications to be truly decisive.

__Systematically explore the parameter space with large-scale studies__. In many cases, tES study design and parameter selection is based on conventions, instead of evidence that the chosen protocol is the optimal one. This will require a better understanding of the neural mechanisms of tES, which is best pursued with animal- or simulation studies. But also at the level of human research, we can take a few steps back and further explore the basic protocols, before taking tES in entirely new directions. It is encouraging that there are new initiatives for multi-center studies that will contribute to this goal.

__Add more control conditions: additional tasks and stimulation sites__. Both null and positive findings have greater scientific value and are easier to interpret with more tightly controlled experimental designs [@DeGraaf2018; @Parkin2015; @Polania2018]. Control tasks can demonstrate to what extent a putative enhancement is task-specific, and can also uncover whether enhancements in one domain do not come with potential costs in another  [@Iuculano2013; @Brem2014a]. Similarly, control stimulation waveforms or sites can demonstrate how specific a putative enhancement is for a particular stimulation protocol. For example, one shortcoming of all studies in this thesis is they they lacked a sham condition, which makes it hard to discern the effects of anodal/cathodal tDCS from random variation. Note though that some recent studies suggest that participants are not as blind to sham conditions as it originally seemed [@Turi2019; @Greinacher2018]. Therefore, applying tES at another location (for which no effects are expected) may provide a better control condition.

__Combine tES with neuroimaging__. Neuroimaging techniques such as (f)MRI and EEG can both inform and augment tES studies [@Bergmann2016; @Thut2017]. First, before data collection, the targeted stimulation site can be localized with (f)MRI scans, to aid precision of electrode placement (as in Chapter \@ref(sacc-tDCS)). Likewise, prior results from neuroimaging studies can inform the choice of stimulation waveform. For example, @VanSchouwenburg2019 chose their tACS frequency based on the EEG results in Chapter \@ref(MFBrain), and the target area based on a meta-analysis of fMRI data [@Langner2012]. Second, neuroimaging data may also be collected during or after application of tES. This can serve to better understand the neural mechanisms of tES-induced changes in behavior, for example by examining changes in neural oscillations following tACS. Similarly, neuroimaging may identify factors that drive individual differences in the behavioral outcome of tES, such as baseline brain state.

__Tailor the stimulation dose to individual participants__. Some of the inter-individual variability in tES outcome can perhaps be undercut by adapting the montage and stimulation parameters such that everyone receives the same dose. This will require further developments in the computational modelling of current flow. But this field is progressing steadily: the model parameters have been validated using recordings of the electric field in humans [@Huang2017; @Opitz2016], and the analytical pipelines are increasingly user-friendly [@Saturnino2018; @Huang2018]. 

__Design studies with a strong prior on the mechanism__. Given the many levels in between the cellular mechanisms and behavioral outcome of tES, the relationships between those levels are often vaguely defined [@Bestmann2014]. In Chapter \@ref(sacc-tDCS), we had at least a rough idea of how tDCS should affect the functioning of the frontal eye fields, and how this should in turn relate to behavioral changes. In contrast, it might be nigh impossible to make a grounded prediction on the effects of dlPFC-tES on moral reasoning---the technique, the area, and the cognitive function are all simply too complex. We struggled more on this front in Chapters \@ref(AB-tDCS-EEG) and \@ref(AB-tDCS-sEBR), as it is not clear whether and how anodal or cathodal tDCS should affect the attentional blink.

__Test new stimulation protocols that may outperform tES__. Some exciting new techniques have been developed that may expand the range of non-invasive brain stimulation beyond the current techniques. These include transcranial focused ultrasound [@Verhagen2019; @Folloni2019], temporal interference stimulation [@Grossman2017], and intersectional short pulse stimulation [@Voroslakos2018]. All are capable of more powerful and more focal stimulation than current tES protocols, but also face their own challenges and have not been extensively tested in humans.

## Conclusions

In this thesis, I have mainly explored whether tDCS can be used to enhance attention. However, a literature review (Chapter \@ref(tDCS-att-review)) revealed that earlier studies reported mixed results. Likewise, the results of the studies I conducted are not in accord with earlier findings that tDCS may improve spatial (Chapter \@ref(sacc-tDCS)) or temporal (Chapter \@ref(AB-tDCS-EEG), \@ref(AB-tDCS-sEBR)) attention. Finally, sustained attention (Chapter \@ref(MFBrain)) may be an interesting target for enhancement, but a tES study partly based on this work [@VanSchouwenburg2019] did not prove effective either.

Based on this thesis and general developments in the field, the future of tES to study attention appears uncertain. In principle, tES is a promising and versatile technique: as a scientific method, a tool for enhancement, and a clinical treatment. But its potential in all three of these directions is yet to be fulfilled. The scientific appeal of tES lies in its ability to causally manipulate brain activity, which could ultimately be used to arbitrate between different theories on how cognition arises from brain activity. But at present this seems to be out of reach. We simply do not know enough about the basic mechanism of tES, and most studies lack methodological rigor. As long as the basic science on tES is inconclusive, it will be difficult to identify optimal protocols for use in cognitive enhancement and clinical applications as well. Reversely, as long as we don't understand how a particular enhancement or treatment effect comes about, it is of little scientific value [@Duecker2014]. These concerns have been expressed for years, but still hold true to this day:

> When we look at what we have really learned about cognition from tACS, tDCS and tRNS, it is small potatoes. [...] Based on the best available studies, from reputable laboratories, we don’t really know where to put the electrodes, we don’t know how robust is the idea that the effects are excitatory or inhibitory, we don’t know what other behaviors are affected, we haven’t tested the methods with real-world tasks and therefore don’t know how they perform outside the lab, and we have no idea in healthy people if they continue to work after more than 2--3 repeated applications.
>
> --- @Walsh2013

This thesis started out with a rather grand introduction to cognitive enhancement. Some see this future on the horizon already, and point out potential ethical problems in the use of tES for this purpose [@CohenKadosh2012]. The potential of tES has also been recognized beyond academia, as it has gained a lot of attention in the media [@Dubljevic2014]. There is even a group of early adopters who have started to use tES at home [@Jwa2015]---primarily for cognitive enhancement of attention. The interest in tES is further fueled by companies who market tES devices to consumers, along with promises of the stars and the moon [@Santarnecchi2013b]. These are all important developments that scientists should have a voice in. However, when we do, we should not forget to be as skeptical towards others as we can be among ourselves [@Riggall2015; @Steenbergen2016; @Wurzman2016; @Walsh2013]. Certainly, the promises of non-invasive brain stimulation are exciting. But it will require a lot of careful research and steady progress to make them a reality.