# Data, code and materials {#resources-supplement}

\vspace{-12pt}

```{=latex}
\begingroup
\renewcommand*{\arraystretch}{1}
\setlength{\tabcolsep}{0pt}
\setlength{\LTleft}{-20cm plus -1fill}
\setlength{\LTright}{\LTleft}
\footnotesize
```

| Chapter                                  | Resource     | Platform                                  | DOI                                |
|------------------------------------------|--------------|-------------------------------------------|------------------------------------|
| __Chapter \@ref(tDCS-att-review)__ [^ch2] |              |                                           |                                    |
|                                          | overview     | Open Science Framework                    | 10.17605/OSF.IO/KQVAP              |
|                                          |              | <https://osf.io/kqvap/>                   |                                    |
| __Chapter \@ref(sacc-tDCS)__ [^ch3]       |              |                                           |                                    |
|                                          | overview     | Project website                           |                                    |
|                                          |              | <https://lcreteig.github.io/sacc-tDCS>    |                                    |
|                                          | data         | figshare                                  | 10.21942/uva.6462770               |
|                                          |              | <https://doi.org/10.21942/uva.6462770.v1> |                                    |
|                                          | code         | GitHub                                    | 10.5281/zenodo.1410502             |
|                                          |              | <https://github.com/lcreteig/sacc-tDCS>   |                                    |
|                                          | materials    | Open Science Framework                    | 10.17605/OSF.IO/8JPV9              |
|                                          |              | <https://osf.io/8jpv9/>                   |                                    |
| __Chapter \@ref(AB-tDCS-EEG)__           |              |                                           |                                    |
|                                          | overview     | Project website                           |                                    |
|                                          |              | <https://lcreteig.github.io/AB-tDCS>      |                                    |
|                                          | behavioral&nbsp;&nbsp;   | Open Science Framework                    | 10.17605/OSF.IO/RJU7F              |
|                                          | data         | <https://osf.io/rju7f/>                   |                                    |
|                                          | EEG data     | OpenNeuro                                 | 10.18112/openneuro.ds001810.v1.1.0 |
|                                          |              | <https://openneuro.org/datasets/ds001810> |                                    |
|                                          | code         | GitHub                                    | 10.5281/zenodo.3233872             |
|                                          |              | <https://github.com/lcreteig/AB-tDCS>     |                                    |
|                                          | materials    | Open Science Framework                    | 10.17605/OSF.IO/Y6HSF              |
|                                          |              | <https://osf.io/y6hsf>                    |                                    |
| __Chapter \@ref(AB-tDCS-sEBR)__          |              |                                           |                                    |
|                                          | overview     | Project website                           |                                    |
|                                          |              | <https://lcreteig.github.io/AB_tDCS-sEBR> |                                    |
|                                          | data         | Open Science Framework                    | 10.17605/OSF.IO/CW2MA              |
|                                          |              | <https://osf.io/cw2ma/>                   |                                    |
|                                          | code         | Open Science Framework                    | 10.17605/OSF.IO/BMP7S              |
|                                          |              | <https://osf.io/bmp7s/>                   |                                    |
|                                          | materials    | Open Science Framework                    | 10.17605/OSF.IO/PZBGY              |
|                                          |              | <https://osf.io/pzbgy/>                   |                                    |
| __Chapter \@ref(MFBrain)__ [^ch6]         |              |                                           |                                   |
|                                          | overview     | Project website                           |                                    |
|                                          |              | <https://lcreteig.github.io/MFBrain>      |                                    |
|                                          | data         | Open Science Framework                    | 10.17605/OSF.IO/456HE              |
|                                          |              | <https://osf.io/456he/>                   |                                    |
|                                          | code         | Open Science Framework                    | 10.17605/OSF.IO/BNWAP              |
|                                          |              | <https://osf.io/bnwap/>                   |                                    |
|                                          | materials    | Open Science Framework                    | 10.17605/OSF.IO/RZJ2V              |
|                                          |              | <https://osf.io/rzj2v/>                   |                                    |

\endgroup

[^ch2]: _Published as_: Reteig, L. C., Talsma, L. J., van Schouwenburg, M. R., & Slagter, H. A. (2017). Transcranial Electrical Stimulation as a Tool to Enhance Attention. _Journal of Cognitive Enhancement, 1_, 10--25. <https://doi.org/10.1007/s41465-017-0010-y>

[^ch3]: _Published as_: Reteig, L. C., Knapen, T., Roelofs, F. J. F. W., Ridderinkhof, K. R., & Slagter, H. A. (2018). No evidence that frontal eye field tDCS affects latency or accuracy of prosaccades. _Frontiers in Neuroscience_ 12:617. <https://doi.org/10.3389/fnins.2018.00617>

[^ch6]: _Published as_: Reteig, L. C., van den Brink, R. L., Prinssen, S., Cohen, M. X., & Slagter, H. A. (2019). Sustaining attention for a prolonged period of time increases temporal variability in cortical responses. *Cortex, 117*, 16--32. <https://doi.org/10.1016/j.cortex.2019.02.016>

\setlength\beforechapskip{50pt}