# Contributions to the chapters {-}
\chaptermark{Contributions to chapters}
\setlength{\parindent}{0pt}
\small

_The contributions below were specified according to the_ CRediT _system_ [Contributor Roles Taxonomy; <https://www.casrai.org/credit.html>; @Brand2015].

---

__Chapter \@ref(tDCS-att-review)__, published as:

Reteig, L. C., Talsma, L.J., van Schouwenburg, M. R., & Slagter, H. A. (2017). Transcranial Electrical
Stimulation as a Tool to Enhance Attention. _Journal of Cognitive Enhancement, 1_, 10–25. <https://doi.org/10.1007/s41465-017-0010-y>

- __L.C. Reteig__: Conceptualization, Data curation, Project Administration, Resources, Writing - original draft.
- __L.J. Talsma__: Writing - review & editing.
- __M.R. van Schouwenburg__: Writing - review & editing.
- __H.A. Slagter__: Conceptualization, Data curation, Funding Acquisition, Project administration, Supervision, Writing - review & editing.

\begin{list}{}{\leftmargin=1.5em\rightmargin=0pt}
\item
I also thank Marlies Vissers and three anonymous reviewers for providing useful feedback on the pre-publication manuscript.
\end{list}

__Chapter \@ref(sacc-tDCS)__, published as:

Reteig, L. C., Knapen, T., Roelofs, F. J. F. W., Ridderinkhof, K. R., & Slagter, H. A. (2018). No evidence that frontal eye field tDCS affects latency or accuracy of prosaccades. _Frontiers in Neuroscience_ 12:617. <https://doi.org/10.3389/fnins.2018.00617>

- __L.C. Reteig__: Conceptualization, Data curation, Formal analysis, Investigation, Methodology, Project administration, Software, Supervision, Validation, Visualization, Writing - original draft. 
- __T. Knapen__: Methodology, Resources, Validation, Writing - review & editing.
- __F.J.F.W. Roelofs__: Data curation, Investigation, Validation.
- __K.R. Ridderinkhof__: Supervision, Writing - review & editing.
- __H.A. Slagter__: Conceptualization, Funding acquisition, Project administration, Supervision, Writing - review & editing.

\begin{list}{}{\leftmargin=1.5em\rightmargin=0pt}
\item
I also thank Monja Hoven and Floortje Bouwkamp for their assistance in piloting and data collection, and Thiago Costa and David Fischer for reviewing the pre-publication manuscript. The following colleagues graciously shared their MRI data for neuronavigation purposes: Daan van Es, Anouk van Loon, Poppy Watson, Suzanne Oosterwijk, Yaïr Pinto, and Henk Cremers.
\end{list}

__Chapter \@ref(AB-tDCS-EEG)__, in preparation as:

Reteig, L. C., Newman, L. A., Ridderinkhof, K. R., & Slagter, H. A. (n.d.). Effects of tDCS on the attentional blink revisited: A statistical evaluation of a replication attempt.

__Chapter \@ref(AB-tDCS-sEBR)__, in preparation as:

Reteig, L. C., Newman, L. A., Ridderinkhof, K. R., & Slagter, H. A. (n.d.). Spontaneous eye blink rate does not predict attentional blink size, nor the effects of tDCS on attentional blink size.

- __L.C. Reteig__: Conceptualization, Data curation, Formal analysis, Investigation, Methodology, Project administration, Resources, Software, Supervision, Visualization, Writing - original draft, Writing - review & editing.
- __L.A. Newman__: Data curation, Formal analysis, Investigation, Project administration, Writing - review & editing.
- __K.R. Ridderinkhof__: Supervision, Writing - review & editing.
- __H.A. Slagter__: Conceptualization, Funding acquisition, Project administration, Resources, Supervision, Writing - review & editing.

\begin{list}{}{\leftmargin=1.5em\rightmargin=0pt}
\item
I also thank Raquel London for sharing all her experience and materials, as well as Daphne Box and Esther van der Giessen for their assistance in data collection.\newline
\end{list}

__Chapter \@ref(MFBrain)__, published as:

Reteig, L. C., van den Brink, R. L., Prinssen, S., Cohen, M. X., & Slagter, H. A. (2019). Sustaining attention for a prolonged period of time increases temporal variability in cortical responses. *Cortex, 117*, 16--32. <https://doi.org/10.1016/j.cortex.2019.02.016>

- __L.C. Reteig__: Methodology, Software, Formal analysis, Data curation, Writing - Original draft, Visualization.
- __R.L. van den Brink__: Conceptualization, Methodology, Software, Investigation, Data Curation, Writing - Review & Editing, Project Administration.
- __S. Prinssen__: Conceptualization, Methodology, Software, Investigation, Data Curation, Writing - Review & Editing, Project Administration.
- __M.X. Cohen__: Software, Resources.
- __H.A. Slagter__: Conceptualization, Writing - original draft, Writing - Review & Editing, Supervision, Project Administration, Funding Acquisition.

\begin{list}{}{\leftmargin=1.5em\rightmargin=0pt}
\item
I also thank Katherine MacLean for sharing the task code and stimuli used in MacLean et al. (2009) with us, Jonathan Smallwood and one anonymous reviewer for feedback on the pre-publication manuscript, as well as Hilde Huizenga, Raoul Grasman and Robert Zwitser for advice on the multilevel model.
\end{list}
