# List of other publications {-}
\chaptermark{List of other publications}

Alilović, J., Timmermans, B., __Reteig, L. C.__, van Gaal, S., & Slagter, H. A. (2019). No evidence that predictions and attention modulate the first feedforward sweep of cortical information processing. _Cerebral Cortex, 29_ 2261--2278. <https://doi.org/10.1093/cercor/bhz038>\newline

van Schouwenburg, M. R., Sörensen, L. K. A., de Klerk, R., __Reteig, L. C.__, & Slagter, H. A. (2018). No differential effects of two different alpha-band electrical stimulation protocols over fronto-parietal regions on spatial attention. _Frontiers in Neuroscience_ 12:433. <https://doi.org/10.3389/fnins.2018.00433>\newline

Slagter, H. A., Mazaheri, A., __Reteig, L. C.__, Smolders, R., Figee, M., Mantione, M., … Denys, D. (2017). Contributions of the Ventral Striatum to Conscious Perception: An Intracranial EEG Study of the Attentional Blink. _Journal of Neuroscience, 37_, 1081--1089. <https://doi.org/10.1523/jneurosci.2282-16.2016>\newline

Slagter, H. A., Prinssen, S., __Reteig, L. C.__, & Mazaheri, A. (2016). Facilitation and inhibition in attention: Functional dissociation of pre-stimulus alpha activity, P1, and N1 components. _NeuroImage, 125_, 25--35. <https://doi.org/10.1016/j.neuroimage.2015.09.058>

\normalsize
\setlength{\parindent}{1.5em}