# Nederlandse samenvatting (Summary in Dutch) {-}
\chaptermark{Summary in Dutch}
\changelocaltocdepth{0}

::: {lang=nl}

_Neuroplasticiteit van aandacht: Hoe hersenstimulatie en mentale vermoeidheid het aandachtsvermogen beïnvloeden_

\bigskip
<br>

## Achtergrond

Vanaf het allereerste begin streeft de mens ernaar zichzelf te verbeteren. Zelfverbetering is een onlosmakelijk deel van de menselijke aard: zonder gereedschappen en materialen houden we onszelf niet warm, beschermd, en doorvoed---oftewel, niet in leven. De opkomst van nieuwe technologie heeft ons ook in staat gesteld tot zelfverbetering van onze cognitieve vaardigheden. Ons geheugen is bijvoorbeeld uitgebreid door ons vermogen dingen op schrift te kunnen stellen, en onze numerieke vaardigheden zijn toegenomen door middel van computers. Door ontwikkelingen in de biotechnologie lijkt het nu ook mogelijk geworden om cognitie te verbeteren door direct in te grijpen in de menselijke biologie. In dit proefschrift heb ik onderzocht in hoeverre elektrische stimulatie van de hersenen  daarvoor geschikt is. Ik heb daarbij vooral gekeken naar veranderingen (-_plasticiteit_) in de hersenen (_neuro_-) die het richten van de aandacht kunnen beïnvloeden (_neuroplasticiteit van aandacht_). 

De techniek die ik daarvoor gebruikt heb staat bekend als _transcranial Direct Current Stimulation_ (tDCS). De moderne vorm van tDCS is ongeveer 20 jaar oud, maar vergelijkbare technieken werden ook al halverwege de 20e eeuw toegepast, en het stimuleren van de hersenen met elektriciteit is zelfs al eeuwen oud. Bij tDCS worden twee elektroden op het hoofd aangebracht, waarna er een zwakke gelijkstroom tussen wordt geleid (zie Figuur \@ref(fig:figure-1-tDCS)A,B). Een gedeelte van deze stroom bereikt ook het brein, en is in staat de elektrische eigenschappen van zenuwcellen te beïnvloeden. Elke zenuwcel heeft een elektrische spanning, en de hoogte van deze spanning bepaalt of de cel tot activiteit (het vuren van een actiepotentiaal) overgaat. tDCS kan de spanning van zenuwcellen met een kleine hoeveelheid doen toe- of afnemen, en de cel daarmee meer of minder actief maken. Tijdens tDCS gaat onder de _anodale_ elektrode elektrische stroom het brein in, wat voor een toename in activiteit zou moeten zorgen. Onder de andere elektrode (de _cathode_) verlaat de elektrische stroom het brein, wat voor een afname in activiteit zou moeten zorgen (zie Figuur \@ref(fig:figure-1-tDCS)C,D). Dit mechanisme lijkt vrij simpel, maar is niet het hele verhaal: deze effecten treden niet onder alle omstandigheden op, en tDCS kan ook nog andere effecten hebben die complexer in elkaar steken. 

Niettemin blijkt uit dieronderzoek (waarbij de effecten op zenuwcellen direct kunnen worden gemeten) dat anodale/cathodale tDCS inderdaad de activiteit van zenuwcellen verhoogt/verlaagt. Bij mensen kan dit alleen op een indirecte manier getest worden. Maar ook daar lieten de eerste studies met tDCS zien dat stimulatie van motorische hersengebieden de spieractiviteit kan verhogen (anodale tDCS) of verlagen (cathodale tDCS). De effecten van tDCS lijken enkele minuten tot zelfs enkele weken te kunnen aanhouden, afhankelijk van de duur van de stimulatie, en hoe vaak de stimulatie herhaald wordt.

Met tDCS kan dus van buiten de schedel de hersenactiviteit worden beïnvloed. Daarnaast is tDCS in beginsel relatief simpel en goedkoop toe te passen. Vanaf de allereerste opkomst leek tDCS daarom al een veelbelovende manier om in te kunnen grijpen in de menselijke cognitie, direct bij de oorsprong---het brein. Maar welke cognitieve vaardigheid zou het interessantst zijn om te verbeteren met tDCS? In dit proefschrift heb ik me toegespitst op _aandacht_. 

Aandacht is het vermogen ons te focussen op relevante informatie en afleidende informatie te onderdrukken. We doen op elk moment een beroep op ons aandachtsvermogen, omdat de totale hoeveelheid beschikbare informatie veel te groot is om allemaal te kunnen verwerken. Denk aan alle zintuigelijke indrukken die je elke milliseconde binnenkrijgt, de totaliteit van herinneringen die je hebt, of alle gedachtes die in je opkomen over de toekomst. Aandacht stelt ons in staat een selectie te maken uit al deze informatie, en alleen datgene te behouden wat nu relevant is (bijvoorbeeld de betekenis van de tekst die u nu aan het lezen bent), ten koste van niet-relevante informatie (bijvoorbeeld de kleur van de letters).

Aandacht is echter niet onfeilbaar. Soms gaan we zo in iets op, dat we er te veel aandacht aan schenken (bijvoorbeeld het voeren van een telefoongesprek tijdens het autorijden). En soms kost het te veel moeite om onze aandacht er een langere periode bij te houden (bijvoorbeeld als u in één keer dit hele proefschrift zou willen lezen).

## Onderzoeksvragen

Dit proefschrift gaat in brede zin over de korte-termijn plasticiteit van aandachtsprocessen: hoe makkelijk is aandacht te beïnvloeden, en wat zijn de hersenprocessen die aan die veranderingen ten grondslag liggen? In Deel `r ifelse(knitr::is_latex_output(), "\\@ref(part-tDCS)", "__II__")` van dit proefschrift heb ik onderzocht in hoeverre ons aandachtsvermogen verbeterd kan worden met tDCS. In Deel `r ifelse(knitr::is_latex_output(), "\\@ref(part-MF)", "__III__")` heb ik juist "de keerzijde van de medaille" onderzocht: wat gebeurt er als aandacht achteruitgaat, als er een onafgebroken periode een beroep op wordt gedaan?

Het proefschrift begint met een literatuurstudie naar (52) eerdere onderzoeken die met tDCS getracht hebben aandacht te verbeteren (__Hoofdstuk \@ref(tDCS-att-review)__). Dit overzicht schetst een zeer gefragmenteerd beeld van de effectiviteit van tDCS, met grote verschillen in zowel de opzet als de uitkomst van de onderzoeken. Er ontbrak een duidelijke basis voor de grootschalige onderzoeken die ik in eerste instantie van plan was te doen, met herhaalde toepassingen van tDCS in meerdere sessies. In plaats daarvan heb ik besloten dichter bij eerder onderzoek te blijven, in de hoop de consistentie van de huidige literatuur te verbeteren.
    
## Deel `r ifelse(knitr::is_latex_output(), "\\@ref(part-tDCS)", "__II__")`: verbeteren van aandacht met tDCS

De studie van oogbewegingen was een voor de hand liggend onderwerp om mee te beginnen (__Hoofdstuk \@ref(sacc-tDCS)__). Oogbewegingen zijn namelijk innig verweven met visuele aandacht: als je je aandacht richt op een bepaald object in je visuele veld maak je meestal ook een oogbeweging daarnaartoe. De _frontal eye field_ is een belangrijk hersengebied dat betrokken is bij het plannen van oogbewegingen. Zodra de activiteit in de _frontal eye field_ een bepaalde drempelwaarde bereikt, wordt een oogbeweging geïnitieerd. Met anodale tDCS zou de activiteit van de _frontal eye field_ moeten toenemen, zodat die drempelwaarde sneller bereikt wordt, en de reactietijd voor het starten van een oogbeweging dus omlaag gaat. 

In Hoofdstuk \@ref(sacc-tDCS) hebben we met een _eye tracker_ gemeten hoe snel deelnemers een oogbeweging konden maken terwijl hun _frontal eye field_ gestimuleerd werd met tDCS. Anodale of cathodale tDCS bracht daar echter geen verandering in. Ook vonden we geen duidelijk effect op het aantal hele snelle of juist langzame oogbewegingen, noch op de precisie of de accuratesse van de oogbewegingen.

Een van de verklaringen voor het uitblijven van resultaten is dat het oogbewegingssysteem al zo goed als optimaal werkt. De deelnemers deden er gemiddeld slechts 150 milliseconden over om een oogbeweging te initiëren. Wellicht is dat plafond simpelweg niet meer te verlagen. We besloten daarom hierna onze focus te verleggen naar een duidelijke tekortkoming van het aandachtssysteem: de zogenaamde _attentional blink_.

De _attentional blink_ (__Hoofdstuk \@ref(AB-tDCS-EEG)__ en __\@ref(AB-tDCS-sEBR)__) treedt op als er heel veel plaatjes (bijvoorbeeld zwarte letters) kort na elkaar gepresenteerd worden op een computerscherm (zie Figuur \@ref(fig:AB-tDCS-fig-task)). Elke letter blijft slechts een fractie van een seconde staan voordat deze wordt overschreven door de volgende letter. Het wordt interessant als er ook twee andere letters tussen worden geplaatst, bijvoorbeeld eerst een rode, en dan een groene. De eerste gekleurde letter zal je altijd prima kunnen herkennen. Maar onder bepaalde omstandigheden gaat de tweede letter geheel aan je voorbij, ondanks zijn opvallende kleur. Het is alsof het aandachtssysteem na de eerste gekleurde letter even “knippert”, en er geen mogelijkheid meer is om ook de tweede letter te verwerken.

Een eerder onderzoek heeft laten zien dat deze _attentional blink_ met tDCS te beïnvloeden is, maar dat het precieze effect verschilt van individu tot individu. Sommige onderzoeksdeelnemers kregen een kleinere _attentional blink_ tijdens anodale tDCS, en een grotere _blink_ tijdens cathodale tDCS. Voor anderen was deze relatie precies andersom.

In mijn onderzoek in Hoofdstuk \@ref(AB-tDCS-EEG) kon ik deze bevinding echter niet repliceren: er was geen algemeen effect van tDCS, en ook geen relatie tussen de effecten van anodale en cathodale tDCS. Aanvullende analyses suggereren dat deze relatie misschien niet bestaat, of in elk geval veel kleiner is dan verwacht.

Één van de complicerende factoren is dat we weinig weten over de oorzaak van individuele verschillen in de _attentional blink_ en de effecten van tDCS. In Hoofdstuk \@ref(AB-tDCS-sEBR) hebben we gekeken of dopamine niveaus deze individuele verschillen wellicht kunnen verklaren, omdat bekend is dat dopamine betrokken is bij de _attentional blink_, en ook bij de fysiologische effecten van tDCS. Het individuele dopamineniveau hebben we geprobeerd te bepalen aan de hand van de frequentie waarmee iemand met zijn/haar ogen knippert (_spontaneous Eye Blink Rate_, sEBR). Eerder onderzoek heeft namelijk uitgewezen dat individuen die vaker knipperen ook hogere dopamine-niveaus lijken te hebben. In Hoofdstuk \@ref(AB-tDCS-sEBR) bleek sEBR echter niet voorspellend voor de grootte van de _attentional blink_, in tegenstelling tot eerder onderzoek. Ook vond ik geen verband tussen sEBR en het effect van tDCS op de _attentional blink_.

De _attentional blink_ is weliswaar een interessant fenomeen, maar wel een die alleen onder zeer specifieke omstandigheden optreedt. In het laatste hoofdstuk heb ik me gericht op een tekortkoming in aandacht die meer uit het dagelijks leven gegrepen is: vermoeidheid.

## Deel `r ifelse(knitr::is_latex_output(), "\\@ref(part-MF)", "__III__")`: verslechteringen in aandacht door mentale vermoeidheid

De ervaring leert dat aandacht niet onuitputtelijk is: na een lange periode van concentratie verslapt aandacht onvermijdelijk. Iedereen zal een dergelijke vermoeidheid na een lange dag werken herkennen, maar voor sommige beroepen kunnen de gevolgen hiervan rampzalig zijn. Denk bijvoorbeeld aan piloten die constant alle metertjes in de gaten moeten houden, of strandwachten die de horizon afspeuren naar potentiële drenkelingen. Het zou een enorme uitkomst zijn als de aandachtsspanne op de een of andere manier verlengd zou kunnen worden---wellicht zelfs met tDCS. Maar daarvoor moeten we eerst begrijpen wat precies de oorzaak is van een dergelijke achteruitgang in aandacht, en welke hersenprocessen daaraan ten grondslag liggen.

In __Hoofdstuk \@ref(MFBrain)__ heb ik dat onderzocht door deelnemers 80 minuten lang onafgebroken een taak te laten uitvoeren, waarbij ze elke twee seconden een lang of een kort lijntje te zien kregen (zie Figuur \@ref(fig:MFBrain-figure-1-task)). De deelnemers moesten alleen op de korte lijntjes reageren door op een knop te drukken, en de lange lijntjes negeren. Bij dit soort taken zie je meestal dat de vermoeidheid snel toeslaat, en er dus steeds meer fouten gemaakt worden. Inderdaad zagen we dat na 20 minuten de taakprestatie al enorm gedaald was. 

De uiteindelijke oorzaak van die daling is daarmee echter nog niet duidelijk: is de taak echt niet meer vol te houden, of raken mensen simpelweg verveeld, of zijn ze niet meer gemotiveerd? Dat hebben we getoetst door na 60 minuten de deelnemers te verrassen met de kans een bonusbedrag te verdienen als ze hun taakprestatie weer omhoog wisten te schroeven. Dat gebeurde inderdaad, maar toch lukte het de meeste deelnemers slechts gedeeltelijk, en bovendien tijdelijk: de taakprestatie werd niet meer zo hoog als in het begin, en zakte op een gegeven moment onvermijdelijk weer in. Dit suggereert dat motivatie weliswaar een belangrijke factor is, maar de invloed van motivatie niet groot genoeg is---op een gegeven moment lijkt "de tank echt leeg".

Tijdens de taak werd ook de hersenactiviteit van de deelnemers gemeten met elektro-encefalografie (EEG). We hebben in het EEG naar drie verschillende aandachts-gerelateerde signalen gekeken, om te bepalen welk aspect van aandacht nu precies achteruit ging. Ten eerste hebben we gekeken naar alfa oscillaties: ritmische fluctuaties in het EEG-signaal rond de 10 Hz (10 pieken per seconde). Uit de amplitude van alfha oscillaties valt informatie af te leiden over _voorbereidende aandacht_ (vóór dat de lijntjes op het scherm verschenen). Ten tweede hebben we gekeken naar _vroege aandachtsprocessen_ (kort nadat de lijntjes op het scherm verschenen) door middel van de P1 en N1 componenten: pieken in het EEG-signaal die veroorzaakt worden door het waarnemen van een visuele stimulus (100-200 milliseconden na het verschijnen). Deze pieken worden groter/kleiner in de aan-/afwezigheid van aandacht. Ten derde hebben we gekeken naar _late aandachtsprocessen_ (~500 milliseconden na het verschijnen van de lijntjes) aan de hand van theta oscillaties (ongeveer 6 Hz). Het verloop van deze theta oscillaties zegt iets over de consistentie in timing van de hersenactiviteit die door de lijntjes wordt opgewekt: reageert het brein elke keer dat er een lijntje wordt waargenomen op hetzelfde moment?

Alleen in dit laatste signaal zagen we hetzelfde patroon als in de taakprestatie over de 80 minuten: een snelle afname, gevolgd door een toename na de verandering in motivatie. Het lijkt er dus op dat vooral de _stabiliteit_ van aandacht veranderd: een afnemende taakprestatie hield verband met een steeds variabelere timing van de hersenactiviteit die door de lijntjes werd opgewekt (de ene keer reageerde het brein vroeger; de andere keer later).

Het experiment uit Hoofdstuk \@ref(MFBrain) gaf aanknopingspunten voor vervolgonderzoek van collega's (niet opgenomen in dit proefschrift) met tDCS. Het doel was het verval in taakprestatie teniet te doen of af te remmen door de betrokken hersengebieden te stimuleren. Helaas bleek noch anodale noch cathodale tDCS effectief: er was geen verschil in achteruitgang op de taak uit Hoofdstuk \@ref(MFBrain). Ook hebben zij de stimulatie toegepast met een wisselstroom van 6 Hz (met transcranial _Alternating_ Current Stimulation), mede geïnspireerd door de EEG bevindingen uit Hoofdstuk \@ref(MFBrain). Dit leidde echter ook niet tot het gewenste effect.

## Conclusie

Al met al bieden geen van de bevindingen in dit proefschrift duidelijk bewijs voor de stelling dat elektrische hersenstimulatie (in de vorm van tDCS) gebruikt kan worden om aandacht te verbeteren. Deze conclusie staat niet op zich: ook in de wetenschappelijke literatuur zijn er de afgelopen jaren steeds meer studies opgedoken die suggereren dat de effecten van tDCS kleiner zijn dan gehoopt.

In het afsluitende deel van dit proefschrift (Deel `r ifelse(knitr::is_latex_output(), "\\@ref(part-conclusion)", "__IV__")`) onderscheid ik drie verklaringen voor het ontbreken van de gewenste resultaten. De eerste is al de revue gepasseerd: namelijk dat het aandachtssysteem in gezonde jongvolwassenen al bijna optimaal functioneert, en er simpelweg geen ruimte meer is voor verbetering. Wellicht liggen er meer kansen bij mensen die kampen met aandachtsproblemen, bijvoorbeeld gerelateerd aan ADHD, veroudering, of beroertes. Dat is in dit proefschrift niet onderzocht.

Ten tweede lijkt er lang te simpel te zijn gedacht over de toepassingen van tDCS. In werkelijkheid is er nog weinig bekend over de precieze mechanismen die aan de werking ten grondslag liggen. Ook blijkt het moeilijk om de techniek zo op te zetten dat er de juiste hoeveelheid stroom door het juiste hersengebied loopt. Hiervoor moet men de elektroden op de juiste plek aanbrengen, in de juiste vorm en grootte, moet de stimulatie de juiste intensiteit hebben, en de juiste tijdsduur aanhouden. Vaak is het helemaal niet duidelijk wat de juiste keuze is, en als klap op de vuurpijl verschilt de juiste keuze vaak ook nog van individu tot individu.

Ten derde is er de afgelopen jaren een "reproduceerbaarheidscrisis" binnen het psychologisch onderzoek aan het licht gekomen. Het lijkt erop dat richtlijnen voor goed onderzoek lange tijd niet zo strikt zijn gevolgd als zou moeten, en dat daardoor effecten kleiner bleken dan verwacht, of bij herhaling van de studie helemaal niet meer te vinden waren. Ook is er de zorg dat veel "nulresultaten" (zoals in dit proefschrift) zijn achtergehouden, omdat "positieve bevindingen" nu eenmaal beter gewaardeerd worden en makkelijker te publiceren zijn. Deze ontwikkelingen zijn geenszins specifiek voor tDCS onderzoek, maar hebben daarop wellicht wel een bovengemiddeld grote uitwerking gehad, omdat het onderzoeksveld nog relatief nieuw is.

Ondanks de tegenvallende resultaten is er nog steeds veel interesse voor tDCS, bijvoorbeeld als behandelmiddel voor neurologische of psychiatrische stoornissen. Er zijn zelfs mensen die op eigen houtje thuis met hersenstimulatie aan de gang gaan. Dat soort praktische toepassingen van tDCS lijken echt nog te voorbarig, omdat zelfs onder gecontroleerde omstandigheden in wetenschappelijke laboratoria de uitkomst van hersenstimulatie niet makkelijk blijkt te voorspellen. Ondanks dat de praktijk weerbarstig blijkt, blijft de potentie van de techniek wel groot. Maar het is ook duidelijk dat de huidige aanpak niet voldoet. Om de optimale toepassingen van hersenstimulatie te vinden zal er nog veel grootschalig onderzoek in grote samenwerkingsverbanden nodig zijn.

:::